# Generated by Django 3.0.3 on 2020-03-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOdesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='ПІБ')),
                ('residence_address', models.CharField(max_length=100, verbose_name='адреса проживання')),
                ('registration_address', models.CharField(max_length=100, verbose_name='адреса реєстрації')),
                ('passport_series', models.CharField(max_length=2, verbose_name='серія паспорту')),
                ('passport_number', models.CharField(max_length=6, verbose_name='номер паспорту')),
                ('who_issued_passport', models.CharField(max_length=100, verbose_name='ким виданий паспорт')),
                ('when_passport_is_issued', models.DateField(verbose_name='коли виданий паспорт')),
                ('rnokpp', models.CharField(max_length=10, verbose_name='реєстраційний номер облікової картки платника податків')),
                ('phone_number', models.CharField(max_length=15, verbose_name='номер телефону')),
            ],
        ),
    ]
