# Generated by Django 3.0.3 on 2020-03-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0002_clientodesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='ПІБ')),
                ('phone_number', models.CharField(max_length=15, verbose_name='номер телефону')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorOdesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='ПІБ')),
                ('phone_number', models.CharField(max_length=15, verbose_name='номер телефону')),
            ],
        ),
    ]
