# Generated by Django 3.0.3 on 2020-03-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0004_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarOdesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, verbose_name='Марка')),
                ('model', models.CharField(max_length=20, verbose_name='Модель')),
                ('production_year', models.IntegerField(verbose_name='Рік випуску')),
                ('car_body_number', models.CharField(max_length=30, verbose_name='Номер кузова')),
                ('license_plate', models.CharField(max_length=30, verbose_name='Номерний знак')),
            ],
        ),
    ]
