# Generated by Django 3.0.3 on 2020-03-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0005_carodesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=10, verbose_name='Номер контракту')),
                ('contract_city', models.CharField(max_length=10, verbose_name='Місто, де заключений контракт')),
                ('contract_date', models.DateField(verbose_name='Дата контракту')),
                ('investor_full_name', models.CharField(max_length=50, verbose_name='ПІБ інвестора')),
                ('director_full_name', models.CharField(max_length=50, verbose_name='ПІБ директора фірми/філіалу фірми')),
                ('client_full_name', models.CharField(max_length=50, verbose_name='ПІБ клієнта')),
                ('initial_cost_car_usd', models.FloatField(verbose_name='Вартість автомобіля в доларах, на момент складання контракту')),
                ('initial_cost_car_uah', models.FloatField(verbose_name='Вартість автомобіля в гривні, на момент складання контракту')),
                ('contract_period_days', models.IntegerField(verbose_name='Строк контракту, в днях')),
                ('contract_period_years', models.IntegerField(verbose_name='Строк контракту, в роках')),
                ('frequency_payment', models.CharField(max_length=10, verbose_name='Періодичність оплати')),
                ('amount_payment_usd', models.FloatField(verbose_name='Сума платежу в доларах')),
            ],
        ),
    ]
