# Generated by Django 3.0.3 on 2020-04-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0008_investorcontract_investorcontractodesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontract',
            name='amount_payment_uah',
            field=models.FloatField(null=True, verbose_name='Сума платежу в гривнях'),
        ),
        migrations.AddField(
            model_name='clientcontract',
            name='commercial_course_usd',
            field=models.FloatField(null=True, verbose_name='Комерційний курс долара'),
        ),
    ]
