# Generated by Django 3.0.3 on 2020-04-01 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0009_auto_20200401_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_color',
            field=models.CharField(max_length=30, null=True, verbose_name='Колір'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_mileage',
            field=models.IntegerField(null=True, verbose_name='Пробіг'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number_2',
            field=models.CharField(max_length=15, null=True, verbose_name='номер телефону 2'),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number_3',
            field=models.CharField(max_length=15, null=True, verbose_name='номер телефону 3'),
        ),
        migrations.AddField(
            model_name='investorcontract',
            name='іnterest_rate',
            field=models.FloatField(null=True, verbose_name='Процентна ставка'),
        ),
    ]
