# Generated by Django 3.0.3 on 2020-04-02 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0010_auto_20200401_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcontract',
            name='contract_period_years',
        ),
        migrations.RemoveField(
            model_name='investorcontract',
            name='amount_payment_usd',
        ),
        migrations.RemoveField(
            model_name='investorcontract',
            name='frequency_payment',
        ),
    ]
