# Generated by Django 3.0.3 on 2020-04-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0011_auto_20200402_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorcontract',
            name='contract_period_years',
        ),
    ]
