# Generated by Django 3.0.3 on 2020-04-03 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0013_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_color',
        ),
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.Color'),
        ),
    ]
