# Generated by Django 3.0.3 on 2020-04-08 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0014_auto_20200403_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontract',
            name='full_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.Client'),
        ),
    ]
