# Generated by Django 3.0.3 on 2020-04-12 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0015_clientcontract_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContractTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=10, verbose_name='Номер контракту')),
                ('contract_city', models.CharField(max_length=10, verbose_name='Місто, де заключений контракт')),
                ('contract_date', models.DateField(verbose_name='Дата контракту')),
                ('investor_full_name', models.CharField(max_length=50, verbose_name='ПІБ інвестора')),
                ('director_full_name', models.CharField(max_length=50, verbose_name='ПІБ директора фірми/філіалу фірми')),
                ('client_full_name', models.CharField(max_length=50, verbose_name='ПІБ клієнта')),
                ('initial_cost_car_usd', models.FloatField(verbose_name='Вартість автомобіля в доларах, на момент складання контракту')),
                ('commercial_course_usd', models.FloatField(null=True, verbose_name='Комерційний курс долара')),
                ('initial_cost_car_uah', models.FloatField(verbose_name='Вартість автомобіля в гривні, на момент складання контракту')),
                ('contract_period_days', models.IntegerField(verbose_name='Строк контракту, в днях')),
                ('frequency_payment', models.CharField(max_length=10, verbose_name='Періодичність оплати')),
                ('amount_payment_usd', models.FloatField(verbose_name='Сума платежу в доларах')),
                ('amount_payment_uah', models.FloatField(null=True, verbose_name='Сума платежу в гривнях')),
                ('full_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.Client')),
            ],
        ),
    ]
