# Generated by Django 3.0.3 on 2020-04-13 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0016_clientcontracttimetable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientcontract',
            old_name='full_name',
            new_name='client',
        ),
        migrations.RemoveField(
            model_name='clientcontracttimetable',
            name='amount_payment_uah',
        ),
        migrations.RemoveField(
            model_name='clientcontracttimetable',
            name='amount_payment_usd',
        ),
        migrations.RemoveField(
            model_name='clientcontracttimetable',
            name='client_full_name',
        ),
        migrations.RemoveField(
            model_name='clientcontracttimetable',
            name='commercial_course_usd',
        ),
        migrations.RemoveField(
            model_name='clientcontracttimetable',
            name='contract_city',
        ),
        migrations.RemoveField(
            model_name='clientcontracttimetable',
            name='contract_date',
        ),
        migrations.RemoveField(
            model_name='clientcontracttimetable',
            name='contract_number',
        ),
        migrations.RemoveField(
            model_name='clientcontracttimetable',
            name='contract_period_days',
        ),
        migrations.RemoveField(
            model_name='clientcontracttimetable',
            name='director_full_name',
        ),
        migrations.RemoveField(
            model_name='clientcontracttimetable',
            name='frequency_payment',
        ),
        migrations.RemoveField(
            model_name='clientcontracttimetable',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='clientcontracttimetable',
            name='initial_cost_car_uah',
        ),
        migrations.RemoveField(
            model_name='clientcontracttimetable',
            name='initial_cost_car_usd',
        ),
        migrations.RemoveField(
            model_name='clientcontracttimetable',
            name='investor_full_name',
        ),
        migrations.AddField(
            model_name='clientcontracttimetable',
            name='client_contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.ClientContract'),
        ),
        migrations.AddField(
            model_name='clientcontracttimetable',
            name='planned_payment_date',
            field=models.DateField(null=True, verbose_name='Планова дата платежу'),
        ),
        migrations.AddField(
            model_name='clientcontracttimetable',
            name='real_payment_date',
            field=models.DateField(null=True, verbose_name='Дійсна дата платежу'),
        ),
    ]
