# Generated by Django 3.0.3 on 2020-04-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0017_auto_20200413_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontracttimetable',
            name='amount_paid_usd',
            field=models.FloatField(null=True, verbose_name='Оплачена сума, в доларах'),
        ),
    ]
