# Generated by Django 3.0.3 on 2020-04-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0018_clientcontracttimetable_amount_paid_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontracttimetable',
            name='planned_payment_date',
            field=models.DateField(editable=False, null=True, verbose_name='Планова дата платежу'),
        ),
    ]
