# Generated by Django 3.0.3 on 2020-04-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0019_auto_20200413_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontracttimetable',
            name='planned_payment_date',
            field=models.DateField(null=True, verbose_name='Планова дата платежу'),
        ),
    ]
