# Generated by Django 3.0.3 on 2020-04-13 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0020_auto_20200413_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontract',
            name='car',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.Car'),
        ),
    ]
