# Generated by Django 3.0.3 on 2020-04-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0023_auto_20200417_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorcontract',
            name='period_1_percentage',
            field=models.FloatField(default=0, verbose_name='Відсоток на період 1'),
        ),
        migrations.AddField(
            model_name='investorcontract',
            name='period_2_percentage',
            field=models.FloatField(default=0, verbose_name='Відсоток на період 2'),
        ),
        migrations.AddField(
            model_name='investorcontract',
            name='period_3_percentage',
            field=models.FloatField(default=0, verbose_name='Відсоток на період 3'),
        ),
        migrations.AddField(
            model_name='investorcontract',
            name='period_4_percentage',
            field=models.FloatField(default=0, verbose_name='Відсоток на період 4'),
        ),
    ]
