# Generated by Django 3.0.3 on 2020-04-27 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0024_auto_20200417_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontract',
            name='frequency_payment',
            field=models.IntegerField(choices=[('0', 'понеділок'), ('1', 'вівторок'), ('2', 'середа'), ('3', 'четвер'), ('4', "п'ятниця")], verbose_name='Періодичність оплати'),
        ),
    ]
