# Generated by Django 3.0.3 on 2020-04-30 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0025_auto_20200427_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontract',
            name='frequency_payment',
            field=models.IntegerField(choices=[(0, 'понеділок'), (1, 'вівторок'), (2, 'середа'), (3, 'четвер'), (4, "п'ятниця")], verbose_name='Періодичність оплати'),
        ),
        migrations.AlterField(
            model_name='investorcontract',
            name='period_1',
            field=models.DateField(null=True, verbose_name='Кінцева дата погашення (період 1)'),
        ),
        migrations.AlterField(
            model_name='investorcontract',
            name='period_1_percentage',
            field=models.FloatField(default=0, verbose_name='Частина основного боргу, у відсотках (період 1)'),
        ),
        migrations.AlterField(
            model_name='investorcontract',
            name='period_2',
            field=models.DateField(null=True, verbose_name='Кінцева дата погашення (період 2)'),
        ),
        migrations.AlterField(
            model_name='investorcontract',
            name='period_2_percentage',
            field=models.FloatField(default=0, verbose_name='Частина основного боргу, у відсотках (період 2)'),
        ),
        migrations.AlterField(
            model_name='investorcontract',
            name='period_3',
            field=models.DateField(null=True, verbose_name='Кінцева дата погашення (період 3)'),
        ),
        migrations.AlterField(
            model_name='investorcontract',
            name='period_3_percentage',
            field=models.FloatField(default=0, verbose_name='Частина основного боргу, у відсотках (період 3)'),
        ),
        migrations.AlterField(
            model_name='investorcontract',
            name='period_4',
            field=models.DateField(null=True, verbose_name='Кінцева дата погашення (період 4)'),
        ),
        migrations.AlterField(
            model_name='investorcontract',
            name='period_4_percentage',
            field=models.FloatField(default=0, verbose_name='Частина основного боргу, у відсотках (період 4)'),
        ),
        migrations.CreateModel(
            name='InvestorContractBodyTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField(null=True, verbose_name='Планова кінцева дата погашення')),
                ('period_percentage', models.FloatField(default=0, verbose_name='Частина основного боргу, у відсотках')),
                ('period_percentage_usd', models.FloatField(default=0, verbose_name='Частина основного боргу, у доларах')),
                ('real_payment_date', models.DateField(null=True, verbose_name='Дійсна дата платежу')),
                ('amount_paid_usd', models.FloatField(null=True, verbose_name='Оплачена сума, в доларах')),
                ('investor_contract', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.InvestorContract')),
            ],
        ),
    ]
