# Generated by Django 3.0.3 on 2020-05-01 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0026_auto_20200430_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorcontractbodytimetable',
            name='amount_paid_usd',
        ),
        migrations.RemoveField(
            model_name='investorcontractbodytimetable',
            name='real_payment_date',
        ),
    ]
