# Generated by Django 3.0.3 on 2020-05-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0027_auto_20200501_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorcontract',
            name='number_periods',
            field=models.IntegerField(default=4, verbose_name='Кількість періодів'),
        ),
    ]
