# Generated by Django 3.0.3 on 2020-05-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0029_investorcontractbodypayment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investorcontractbodytimetable',
            options={'ordering': ['period']},
        ),
        migrations.AddField(
            model_name='investorcontract',
            name='status_body',
            field=models.FloatField(null=True, verbose_name='Стан розрахунку по тілу кредита. Переплата/прострочка (-)'),
        ),
    ]
