# Generated by Django 3.0.3 on 2020-05-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0032_auto_20200505_1316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorcontract',
            name='period_1',
        ),
        migrations.RemoveField(
            model_name='investorcontract',
            name='period_1_percentage',
        ),
        migrations.RemoveField(
            model_name='investorcontract',
            name='period_2',
        ),
        migrations.RemoveField(
            model_name='investorcontract',
            name='period_2_percentage',
        ),
        migrations.RemoveField(
            model_name='investorcontract',
            name='period_3',
        ),
        migrations.RemoveField(
            model_name='investorcontract',
            name='period_3_percentage',
        ),
        migrations.RemoveField(
            model_name='investorcontract',
            name='period_4',
        ),
        migrations.RemoveField(
            model_name='investorcontract',
            name='period_4_percentage',
        ),
        migrations.AddField(
            model_name='investorcontract',
            name='last_month_percentage',
            field=models.FloatField(null=True, verbose_name='Відсотки за попередній місяць'),
        ),
        migrations.AddField(
            model_name='investorcontract',
            name='status_percentage',
            field=models.FloatField(null=True, verbose_name='Стан розрахунку по відсотках кредиту. Прострочка (-)'),
        ),
    ]
