# Generated by Django 3.0.3 on 2020-05-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0033_auto_20200509_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorcontractpercentagepayment',
            name='planned_amount_payment_usd',
        ),
        migrations.RemoveField(
            model_name='investorcontractpercentagepayment',
            name='planned_payment_date',
        ),
    ]
