# Generated by Django 3.0.3 on 2020-05-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0034_auto_20200509_1254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investorcontractpercentagepayment',
            old_name='real_payment_date',
            new_name='date',
        ),
    ]
