# Generated by Django 3.0.3 on 2020-05-09 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0035_auto_20200509_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investorcontractpercentagepayment',
            old_name='amount_paid_usd',
            new_name='sum',
        ),
    ]
