# Generated by Django 3.0.3 on 2020-05-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0036_auto_20200509_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontract',
            name='frequency_payment',
            field=models.IntegerField(choices=[(0, 'понеділок'), (1, 'вівторок'), (2, 'середа'), (3, 'четвер'), (4, "п'ятниця"), (5, 'субота')], verbose_name='Періодичність оплати'),
        ),
    ]
