# Generated by Django 3.0.3 on 2020-05-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0039_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateKyiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата')),
                ('sum', models.FloatField(null=True, verbose_name='Курс, 1$ = (грн) ')),
            ],
        ),
    ]
