# Generated by Django 3.0.3 on 2020-05-15 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0042_clientcontract_number_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorcontract',
            name='specification_number',
            field=models.IntegerField(null=True, verbose_name='Номер специфікації контракту'),
        ),
        migrations.AlterField(
            model_name='investorcontract',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Номер контракту'),
        ),
    ]
