# Generated by Django 3.0.3 on 2020-05-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0043_auto_20200515_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorcontract',
            name='last_month_percentage',
            field=models.FloatField(default=0.0, null=True, verbose_name='Відсотки за попередній місяць'),
        ),
    ]
