# Generated by Django 3.0.3 on 2020-05-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0045_auto_20200528_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorcontract',
            name='last_month_percentage',
            field=models.FloatField(default=1.11, null=True, verbose_name='Відсотки за попередній місяць'),
        ),
    ]
