# Generated by Django 3.0.3 on 2020-05-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0048_auto_20200530_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number_3',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='номер телефону 3'),
        ),
    ]
