# Generated by Django 3.0.3 on 2020-06-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0049_auto_20200530_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontractto',
            name='note',
            field=models.TextField(null=True, verbose_name='Примітки'),
        ),
    ]
