# Generated by Django 3.0.3 on 2020-06-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0052_auto_20200602_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='passport_number',
        ),
        migrations.RemoveField(
            model_name='client',
            name='passport_series',
        ),
        migrations.AddField(
            model_name='client',
            name='passport_data',
            field=models.CharField(max_length=6, null=True, verbose_name='дані  паспорту (серія + номер), чи іншого документу'),
        ),
    ]
