# Generated by Django 3.0.3 on 2020-06-03 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0059_auto_20200603_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcontract',
            name='commercial_course_usd_new',
        ),
    ]
