# Generated by Django 3.0.3 on 2020-06-03 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0063_remove_clientcontract_commercial_course_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontract',
            name='commercial_course_usd_test',
            field=models.ForeignKey(limit_choices_to={'date': models.DateField(verbose_name='Дата контракту')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.ExchangeRateKyiv'),
        ),
    ]
