# Generated by Django 3.0.3 on 2020-06-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0065_auto_20200603_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontract',
            name='commercial_course_usd_test',
            field=models.FloatField(verbose_name='Комерційний курс долара test'),
        ),
    ]
