# Generated by Django 3.0.3 on 2020-06-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0066_auto_20200604_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontract',
            name='commercial_course_usd_test',
            field=models.FloatField(default=0, verbose_name='Комерційний курс долара test'),
        ),
    ]
