# Generated by Django 3.0.3 on 2020-06-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0068_auto_20200604_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeratelviv',
            name='date',
            field=models.DateField(null=True, unique=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='exchangerateodesa',
            name='date',
            field=models.DateField(null=True, unique=True, verbose_name='Дата'),
        ),
    ]
