# Generated by Django 3.0.3 on 2020-06-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0069_auto_20200604_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investorcontract',
            name='number',
            field=models.IntegerField(default=None, null=True, verbose_name='Номер контракту'),
        ),
        migrations.AlterField(
            model_name='investorcontract',
            name='specification_number',
            field=models.IntegerField(default=None, null=True, verbose_name='Номер специфікації контракту'),
        ),
    ]
