# Generated by Django 3.0.3 on 2020-06-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0070_auto_20200604_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontract',
            name='initial_cost_car_uah',
            field=models.FloatField(default=0, verbose_name='Вартість автомобіля в гривні, на момент складання контракту'),
        ),
    ]
