# Generated by Django 3.0.3 on 2020-06-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0072_auto_20200624_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontract',
            name='status_body',
            field=models.FloatField(default=0, verbose_name='Стан розрахунку по кредиту. Переплата/прострочка (-)'),
        ),
    ]
