# Generated by Django 3.0.3 on 2020-06-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0076_auto_20200624_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontract',
            name='amount_payment_TO_uah',
            field=models.FloatField(default=0, null=True, verbose_name='Сума на ТО, в гривнях'),
        ),
        migrations.AlterField(
            model_name='clientcontract',
            name='balance_TO_uah',
            field=models.FloatField(default=0, null=True, verbose_name='Залишок по ТО, в гривнях'),
        ),
    ]
