# Generated by Django 3.0.3 on 2020-06-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0080_auto_20200624_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontracttimetable',
            name='note',
            field=models.CharField(max_length=100, null=True, verbose_name='Примітки'),
        ),
    ]
