# Generated by Django 3.0.3 on 2020-07-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0081_clientcontracttimetable_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContractWeeklyCarReport',
            fields=[
            ],
            options={
                'verbose_name': 'Клієнтський контракт, Тижневий звіт по авто',
                'verbose_name_plural': 'Клієнтський контракт, Тижневий звіт по авто',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cars_rental.clientcontract',),
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Відділення', 'verbose_name_plural': 'Відділення'},
        ),
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Автомобіль', 'verbose_name_plural': 'Автомобілі'},
        ),
        migrations.AlterModelOptions(
            name='carodesa',
            options={'verbose_name': 'Автомобіль (Одеса)', 'verbose_name_plural': 'Автомобілі (Одеса)'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клієнт', 'verbose_name_plural': 'Клієнти'},
        ),
        migrations.AlterModelOptions(
            name='clientcontract',
            options={'verbose_name': 'Клієнтський контракт', 'verbose_name_plural': 'Клієнтські контракти'},
        ),
        migrations.AlterModelOptions(
            name='clientcontracttimetable',
            options={'verbose_name': 'Клієнтський контракт, графік погашення', 'verbose_name_plural': 'Клієнтський контракт, графік погашення'},
        ),
        migrations.AlterModelOptions(
            name='clientcontractto',
            options={'verbose_name': 'Клієнтський контракт, ТО', 'verbose_name_plural': 'Клієнтський контракт, ТО'},
        ),
        migrations.AlterModelOptions(
            name='clientodesa',
            options={'verbose_name': 'Клієнт (Одеса)', 'verbose_name_plural': 'Клієнти (Одеса)'},
        ),
        migrations.AlterModelOptions(
            name='color',
            options={'verbose_name': 'Колір авто', 'verbose_name_plural': 'Кольори авто'},
        ),
        migrations.AlterModelOptions(
            name='exchangeratekyiv',
            options={'verbose_name': 'Валютний курс (Київ)', 'verbose_name_plural': 'Валютний курс (Київ)'},
        ),
        migrations.AlterModelOptions(
            name='exchangeratelviv',
            options={'verbose_name': 'Валютний курс (Львів)', 'verbose_name_plural': 'Валютний курс (Львів)'},
        ),
        migrations.AlterModelOptions(
            name='exchangerateodesa',
            options={'verbose_name': 'Валютний курс (Одеса)', 'verbose_name_plural': 'Валютний курс (Одеса)'},
        ),
        migrations.AlterModelOptions(
            name='investor',
            options={'verbose_name': 'Інвестор', 'verbose_name_plural': 'Інвестори'},
        ),
        migrations.AlterModelOptions(
            name='investorcontract',
            options={'verbose_name': 'Інвесторський контракт', 'verbose_name_plural': 'Інвесторські контракти'},
        ),
        migrations.AlterModelOptions(
            name='investorcontractbodypayment',
            options={'verbose_name': 'Інвесторський контракт, платежі по тілу кредиту', 'verbose_name_plural': 'Інвесторський контракт, платежі по тілу кредиту'},
        ),
        migrations.AlterModelOptions(
            name='investorcontractbodytimetable',
            options={'ordering': ['payment_date'], 'verbose_name': 'Інвесторський контракт, графік погашення\tтіла кредиту', 'verbose_name_plural': 'Інвесторський контракт, графік погашення тіла кредиту'},
        ),
        migrations.AlterModelOptions(
            name='investorcontractpercentagepayment',
            options={'verbose_name': 'Інвесторський контракт, платежі по % на тіло кредиту', 'verbose_name_plural': 'Інвесторський контракт, платежі по % на тіло кредиту'},
        ),
        migrations.AlterModelOptions(
            name='investorodesa',
            options={'verbose_name': 'Інвестор (Одеса)', 'verbose_name_plural': 'Інвестори (Одеса)'},
        ),
        migrations.AlterField(
            model_name='clientcontracttimetable',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Примітки'),
        ),
        migrations.AlterField(
            model_name='clientcontractto',
            name='note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Примітки'),
        ),
    ]
