# Generated by Django 3.0.3 on 2020-07-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0082_auto_20200706_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontract',
            name='loan_amount_paid_usd',
            field=models.FloatField(default=0, null=True, verbose_name='Сума виплачених платежів'),
        ),
        migrations.AlterField(
            model_name='clientcontract',
            name='loan_amount_to_be_paid_usd',
            field=models.FloatField(default=0, null=True, verbose_name='Сума платежів до оплати'),
        ),
        migrations.AlterField(
            model_name='clientcontract',
            name='status_body_usd',
            field=models.FloatField(default=0, null=True, verbose_name='Стан розрахунку по платежах. Переплата/прострочка (-)'),
        ),
    ]
