# Generated by Django 3.0.3 on 2020-07-07 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0083_auto_20200707_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontractto',
            name='date',
            field=models.DateField(default=datetime.date(2020, 7, 7), null=True, verbose_name='Дата платежу (ТО)'),
        ),
    ]
