# Generated by Django 3.0.3 on 2020-07-08 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0084_auto_20200709_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcontractto',
            options={'ordering': ['date'], 'verbose_name': 'Клієнтський контракт, ТО', 'verbose_name_plural': 'Клієнтський контракт, ТО'},
        ),
        migrations.AlterField(
            model_name='clientcontractto',
            name='date',
            field=models.DateField(default=datetime.date(2020, 7, 8), null=True, verbose_name='Дата платежу (ТО)'),
        ),
    ]
