# Generated by Django 3.0.3 on 2020-07-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0085_auto_20200708_1727'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcontractto',
            options={'verbose_name': 'Клієнтський контракт, ТО', 'verbose_name_plural': 'Клієнтський контракт, ТО'},
        ),
    ]
