# Generated by Django 3.0.3 on 2020-07-09 05:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0087_auto_20200707_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontracttimetable',
            name='planned_amount_payment_usd',
            field=models.FloatField(blank=True, null=True, verbose_name='Планова сума платежу, в доларах'),
        ),
        migrations.AlterField(
            model_name='clientcontractto',
            name='date',
            field=models.DateField(default=datetime.date(2020, 7, 9), null=True, verbose_name='Дата платежу (ТО)'),
        ),
    ]
