# Generated by Django 3.0.3 on 2020-07-09 05:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0089_auto_20200709_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontracttimetable',
            name='planned_payment_date',
            field=models.DateField(default=datetime.date(2020, 7, 9), null=True, verbose_name='Планова дата платежу'),
        ),
    ]
