# Generated by Django 3.0.3 on 2020-07-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0091_auto_20200709_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcontracttimetable',
            name='real_payment_date',
        ),
        migrations.AlterField(
            model_name='clientcontracttimetable',
            name='planned_payment_date',
            field=models.DateField(null=True, verbose_name='Дата платежу'),
        ),
    ]
