# Generated by Django 3.0.3 on 2020-07-07 09:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0093_auto_20200709_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontracttimetable',
            name='planned_payment_date',
            field=models.DateField(default=datetime.date(2020, 7, 7), null=True, verbose_name='Дата платежу'),
        ),
        migrations.AlterField(
            model_name='clientcontractto',
            name='date',
            field=models.DateField(default=datetime.date(2020, 7, 7), null=True, verbose_name='Дата платежу (ТО)'),
        ),
    ]
