# Generated by Django 3.0.3 on 2020-07-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0094_auto_20200707_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontracttimetable',
            name='amount_paid_usd',
            field=models.FloatField(blank=True, null=True, verbose_name='Оплачена сума, в доларах'),
        ),
    ]
