# Generated by Django 3.0.3 on 2020-07-09 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0095_auto_20200707_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontract',
            name='frequency_payment',
            field=models.IntegerField(choices=[(0, 'понеділок'), (1, 'вівторок'), (2, 'середа'), (3, 'четвер'), (4, "п'ятниця"), (5, 'субота')], default=0, verbose_name='Періодичність оплати'),
        ),
        migrations.AlterField(
            model_name='clientcontracttimetable',
            name='planned_payment_date',
            field=models.DateField(default=datetime.date(2020, 7, 9), null=True, verbose_name='Дата платежу'),
        ),
        migrations.AlterField(
            model_name='clientcontractto',
            name='date',
            field=models.DateField(default=datetime.date(2020, 7, 9), null=True, verbose_name='Дата платежу (ТО)'),
        ),
    ]
