# Generated by Django 3.0.3 on 2020-07-10 14:03

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0096_auto_20200709_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontracttimetable',
            name='planned_payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата платежу'),
        ),
        migrations.AlterField(
            model_name='clientcontractto',
            name='date',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Дата платежу (ТО)'),
        ),
    ]
