# Generated by Django 3.0.3 on 2020-08-03 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0097_auto_20200710_1703'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcontractweeklycarreport',
            options={'verbose_name': 'Клієнтський контракт, Тижневий звіт по авто', 'verbose_name_plural': 'Клієнтські контракти, Тижневий звіт по авто'},
        ),
    ]
