# Generated by Django 3.0.3 on 2020-08-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0098_auto_20200803_1542'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car',
            new_name='CarKyiv',
        ),
        migrations.AlterModelOptions(
            name='carkyiv',
            options={'verbose_name': 'Автомобіль (Київ)', 'verbose_name_plural': 'Автомобілі (Київ)'},
        ),
    ]
