# Generated by Django 3.0.3 on 2020-08-03 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0099_auto_20200803_1741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='ClientKyiv',
        ),
        migrations.AlterModelOptions(
            name='clientkyiv',
            options={'verbose_name': 'Клієнт (Київ)', 'verbose_name_plural': 'Клієнти (Київ)'},
        ),
    ]
