# Generated by Django 3.0.3 on 2020-08-04 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0100_auto_20200803_1755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientContractWeeklyCarReport',
        ),
    ]
