# Generated by Django 3.0.3 on 2020-08-04 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0101_delete_clientcontractweeklycarreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLviv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='ПІБ')),
                ('residence_address', models.CharField(max_length=100, verbose_name='адреса проживання')),
                ('registration_address', models.CharField(max_length=100, verbose_name='адреса реєстрації')),
                ('passport_data', models.CharField(max_length=10, null=True, verbose_name='дані  паспорту (серія + номер), чи іншого документу')),
                ('who_issued_passport', models.CharField(max_length=100, verbose_name='ким виданий паспорт')),
                ('when_passport_is_issued', models.DateField(verbose_name='коли виданий паспорт')),
                ('rnokpp', models.CharField(max_length=10, verbose_name='реєстраційний номер облікової картки платника податків')),
                ('phone_number', models.CharField(max_length=15, verbose_name='номер телефону')),
                ('phone_number_2', models.CharField(blank=True, max_length=15, null=True, verbose_name='номер телефону 2')),
                ('phone_number_3', models.CharField(blank=True, max_length=15, null=True, verbose_name='номер телефону 3')),
            ],
            options={
                'verbose_name': 'Клієнт (Львів)',
                'verbose_name_plural': 'Клієнти (Львів)',
            },
        ),
        migrations.CreateModel(
            name='CarLviv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, verbose_name='Марка')),
                ('model', models.CharField(max_length=20, verbose_name='Модель')),
                ('production_year', models.IntegerField(verbose_name='Рік випуску')),
                ('body_number', models.CharField(max_length=30, verbose_name='Номер кузова')),
                ('license_plate', models.CharField(max_length=30, verbose_name='Номерний знак')),
                ('mileage', models.IntegerField(null=True, verbose_name='Пробіг')),
                ('color', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.Color')),
            ],
            options={
                'verbose_name': 'Автомобіль (Львів)',
                'verbose_name_plural': 'Автомобілі (Львів)',
            },
        ),
    ]
