# Generated by Django 3.0.3 on 2020-08-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0102_carlviv_clientlviv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientContractTOToday',
        ),
    ]
