# Generated by Django 3.0.3 on 2020-08-04 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0103_delete_clientcontracttotoday'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientContract',
            new_name='ClientContractKyiv',
        ),
        migrations.RenameModel(
            old_name='ClientContractTimetable',
            new_name='ClientContractTimetableKyiv',
        ),
        migrations.RenameModel(
            old_name='ClientContractTO',
            new_name='ClientContractTOKyiv',
        ),
        migrations.AlterModelOptions(
            name='clientcontractkyiv',
            options={'verbose_name': 'Клієнтський контракт (Київ)', 'verbose_name_plural': 'Клієнтські контракти (Київ)'},
        ),
        migrations.AlterModelOptions(
            name='clientcontracttimetablekyiv',
            options={'verbose_name': 'Клієнтський контракт (Київ), графік погашення', 'verbose_name_plural': 'Клієнтський контракт (Київ), графік погашення'},
        ),
        migrations.AlterModelOptions(
            name='clientcontracttokyiv',
            options={'verbose_name': 'Клієнтський контракт (Київ), ТО', 'verbose_name_plural': 'Клієнтський контракт (Київ), ТО'},
        ),
    ]
