# Generated by Django 3.0.3 on 2020-08-04 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0104_auto_20200804_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContractTOTodayKyiv',
            fields=[
            ],
            options={
                'verbose_name': 'Клієнтський контракт, ТО; введення даних (Київ)',
                'verbose_name_plural': 'Клієнтський контракт, ТО; введення даних (Київ)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cars_rental.clientcontracttokyiv',),
        ),
    ]
