# Generated by Django 3.0.3 on 2020-08-04 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0106_delete_clientodesa'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContractWeeklyCarReportKyiv',
            fields=[
            ],
            options={
                'verbose_name': 'Клієнтський контракт, Тижневий звіт по авто',
                'verbose_name_plural': 'Клієнтські контракти, Тижневий звіт по авто',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cars_rental.clientcontractkyiv',),
        ),
    ]
