# Generated by Django 3.0.3 on 2020-08-04 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0108_auto_20200804_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContractLviv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер контракту')),
                ('number_number', models.IntegerField(null=True, verbose_name='Номер номеру контракту')),
                ('city', models.CharField(max_length=10, verbose_name='Місто, де заключений контракт')),
                ('date', models.DateField(verbose_name='Дата контракту')),
                ('investor_full_name', models.CharField(max_length=50, verbose_name='ПІБ інвестора')),
                ('director_full_name', models.CharField(max_length=50, verbose_name='ПІБ директора фірми/філіалу фірми')),
                ('initial_cost_car_usd', models.FloatField(verbose_name='Вартість автомобіля в доларах, на момент складання контракту')),
                ('commercial_course_usd_test', models.FloatField(default=0, verbose_name='Комерційний курс долара test')),
                ('initial_cost_car_uah', models.FloatField(default=0, verbose_name='Вартість автомобіля в гривні, на момент складання контракту')),
                ('period_days', models.IntegerField(verbose_name='Строк контракту, в днях')),
                ('frequency_payment', models.IntegerField(choices=[(0, 'понеділок'), (1, 'вівторок'), (2, 'середа'), (3, 'четвер'), (4, "п'ятниця"), (5, 'субота')], default=0, verbose_name='Періодичність оплати')),
                ('amount_payment_usd', models.FloatField(verbose_name='Сума платежу в доларах')),
                ('amount_payment_uah', models.FloatField(default=0, verbose_name='Сума платежу в гривнях')),
                ('loan_amount_paid_usd', models.FloatField(default=0, null=True, verbose_name='Сума виплачених платежів')),
                ('loan_amount_to_be_paid_usd', models.FloatField(default=0, null=True, verbose_name='Сума платежів до оплати')),
                ('status_body_usd', models.FloatField(default=0, null=True, verbose_name='Стан розрахунку по платежах. Переплата/прострочка (-)')),
                ('amount_payment_TO_uah', models.FloatField(default=0, null=True, verbose_name='Сума на ТО, в гривнях')),
                ('balance_TO_uah', models.FloatField(default=0, null=True, verbose_name='Залишок по ТО, в гривнях')),
                ('car', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.CarLviv')),
                ('client', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.ClientLviv')),
            ],
            options={
                'verbose_name': 'Клієнтський контракт (Львів)',
                'verbose_name_plural': 'Клієнтські контракти (Львів)',
            },
        ),
    ]
