# Generated by Django 3.0.3 on 2020-08-05 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0109_clientcontractlviv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Investor',
            new_name='InvestorKyiv',
        ),
        migrations.AlterModelOptions(
            name='investorkyiv',
            options={'verbose_name': 'Інвестор (Київ)', 'verbose_name_plural': 'Інвестор (Київ)'},
        ),
    ]
