# Generated by Django 3.0.3 on 2020-08-05 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0110_auto_20200805_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investorkyiv',
            options={'verbose_name': 'Інвестор (Київ)', 'verbose_name_plural': 'Інвестори (Київ)'},
        ),
    ]
