# Generated by Django 3.0.3 on 2020-08-05 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0111_auto_20200805_1108'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcontracttimetablekyiv',
            options={'verbose_name': 'Клієнтський контракт, графік погашення', 'verbose_name_plural': 'Клієнтський контракт, графік погашення'},
        ),
        migrations.AlterModelOptions(
            name='clientcontracttokyiv',
            options={'verbose_name': 'Клієнтський контракт, ТО', 'verbose_name_plural': 'Клієнтський контракт, ТО'},
        ),
        migrations.AlterModelOptions(
            name='clientcontracttotodaykyiv',
            options={'verbose_name': 'Клієнтський контракт, ТО; введення даних', 'verbose_name_plural': 'Клієнтський контракт, ТО; введення даних'},
        ),
    ]
