# Generated by Django 3.0.3 on 2020-08-05 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0113_auto_20200805_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvestorContractBodyTimetable',
            new_name='InvestorContractBodyTimetableKyiv',
        ),
    ]
