# Generated by Django 3.0.3 on 2020-08-05 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0114_auto_20200805_1242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvestorContractOdesa',
        ),
    ]
