# Generated by Django 3.0.3 on 2020-08-05 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0115_delete_investorcontractodesa'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvestorContractBodyPayment',
            new_name='InvestorContractBodyPaymentKyiv',
        ),
    ]
