# Generated by Django 3.0.3 on 2020-08-05 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0116_auto_20200805_1250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvestorContractPercentagePayment',
            new_name='InvestorContractPercentagePaymentKyiv',
        ),
    ]
