# Generated by Django 3.0.3 on 2020-08-05 13:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0117_auto_20200805_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContractTOLviv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, null=True, verbose_name='Дата платежу (ТО)')),
                ('sum', models.FloatField(null=True, verbose_name='Сума платежу (ТО)')),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Примітки')),
                ('client_contract', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.ClientContractLviv')),
            ],
            options={
                'verbose_name': 'Клієнтський контракт, ТО',
                'verbose_name_plural': 'Клієнтський контракт, ТО',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientContractTimetableLviv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_payment_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Дата платежу')),
                ('planned_amount_payment_usd', models.FloatField(blank=True, null=True, verbose_name='Планова сума платежу, в доларах')),
                ('amount_paid_usd', models.FloatField(blank=True, null=True, verbose_name='Оплачена сума, в доларах')),
                ('note', models.CharField(blank=True, max_length=100, null=True, verbose_name='Примітки')),
                ('client_contract', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.ClientContractLviv')),
            ],
            options={
                'verbose_name': 'Клієнтський контракт, графік погашення',
                'verbose_name_plural': 'Клієнтський контракт, графік погашення',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClientContractTOTodayLviv',
            fields=[
            ],
            options={
                'verbose_name': 'Клієнтський контракт, ТО; введення даних',
                'verbose_name_plural': 'Клієнтський контракт, ТО; введення даних',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cars_rental.clientcontracttolviv',),
        ),
    ]
