# Generated by Django 3.0.3 on 2020-08-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0118_clientcontracttimetablelviv_clientcontracttolviv_clientcontracttotodaylviv'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorLviv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='ПІБ')),
                ('phone_number', models.CharField(max_length=15, verbose_name='номер телефону')),
            ],
            options={
                'verbose_name': 'Інвестор (Львів)',
                'verbose_name_plural': 'Інвестори (Львів)',
            },
        ),
    ]
