# Generated by Django 3.0.3 on 2020-08-05 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0120_auto_20200805_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorContractLviv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=None, null=True, verbose_name='Номер контракту')),
                ('specification_number', models.IntegerField(default=None, null=True, verbose_name='Номер специфікації контракту')),
                ('city', models.CharField(max_length=10, verbose_name='Місто, де заключений контракт')),
                ('date', models.DateField(verbose_name='Дата контракту')),
                ('director_full_name', models.CharField(max_length=50, verbose_name='ПІБ директора фірми/філіалу фірми')),
                ('client_full_name', models.CharField(max_length=50, verbose_name='ПІБ клієнта')),
                ('initial_cost_car_usd', models.FloatField(verbose_name='Вартість автомобіля в доларах, на момент складання контракту')),
                ('initial_cost_car_uah', models.FloatField(verbose_name='Вартість автомобіля в гривні, на момент складання контракту')),
                ('period_days', models.IntegerField(verbose_name='Строк контракту, в днях')),
                ('number_periods', models.IntegerField(default=4, verbose_name='Кількість періодів')),
                ('status_body', models.FloatField(null=True, verbose_name='Стан розрахунку по тілу кредита. Переплата/прострочка (-)')),
                ('іnterest_rate', models.FloatField(null=True, verbose_name='Процентна ставка')),
                ('last_month_percentage', models.FloatField(null=True, verbose_name='Відсотки за попередній місяць')),
                ('status_percentage', models.FloatField(null=True, verbose_name='Стан розрахунку по відсотках кредиту. Прострочка (-)')),
                ('car', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.CarLviv')),
                ('investor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.InvestorLviv')),
            ],
            options={
                'verbose_name': 'Інвесторський контракт (Львів)',
                'verbose_name_plural': 'Інвесторські контракти (Львів)',
            },
        ),
    ]
