# Generated by Django 3.0.3 on 2020-08-05 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0121_investorcontractlviv'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorContractBodyTimetableLviv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(null=True, verbose_name='Планова кінцева дата погашення')),
                ('payment_percentage', models.FloatField(default=0, verbose_name='Частина основного боргу, у відсотках')),
                ('payment_usd', models.FloatField(default=0, verbose_name='Частина основного боргу, у доларах')),
                ('investor_contract', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.InvestorContractLviv')),
            ],
            options={
                'verbose_name': 'Інвесторський контракт, графік погашення\tтіла кредиту',
                'verbose_name_plural': 'Інвесторський контракт, графік погашення тіла кредиту',
                'ordering': ['payment_date'],
                'abstract': False,
            },
        ),
    ]
