# Generated by Django 3.0.3 on 2020-08-05 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0122_investorcontractbodytimetablelviv'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorContractPercentagePaymentLviv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дійсна дата платежу')),
                ('sum', models.FloatField(null=True, verbose_name='Оплачена сума, в доларах')),
                ('investor_contract', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.InvestorContractLviv')),
            ],
            options={
                'verbose_name': 'Інвесторський контракт, платежі по % на тіло кредиту',
                'verbose_name_plural': 'Інвесторський контракт, платежі по % на тіло кредиту',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvestorContractBodyPaymentLviv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True, verbose_name='Дата платежу')),
                ('sum', models.FloatField(default=0, verbose_name='Сума платежу (погашення тіла боргу)')),
                ('investor_contract', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.InvestorContractLviv')),
            ],
            options={
                'verbose_name': 'Інвесторський контракт, платежі по тілу кредиту',
                'verbose_name_plural': 'Інвесторський контракт, платежі по тілу кредиту',
                'abstract': False,
            },
        ),
    ]
