# Generated by Django 3.0.3 on 2020-09-10 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0123_investorcontractbodypaymentlviv_investorcontractpercentagepaymentlviv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcontractweeklycarreportkyiv',
            options={'verbose_name': 'Клієнтський контракт (Київ), Тижневий звіт по авто', 'verbose_name_plural': 'Клієнтські контракти (Київ), Тижневий звіт по авто'},
        ),
    ]
