# Generated by Django 3.0.3 on 2020-09-10 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0124_auto_20200910_1050'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContractPeriodCarReportKyiv',
            fields=[
            ],
            options={
                'verbose_name': 'Клієнтський контракт (Київ), звіт по авто за період',
                'verbose_name_plural': 'Клієнтські контракти (Київ), звіт по авто за період',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cars_rental.clientcontractkyiv',),
        ),
    ]
