# Generated by Django 3.0.3 on 2020-09-22 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0125_clientcontractperiodcarreportkyiv'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientContractWeeklyCarTOReportKyiv',
            fields=[
            ],
            options={
                'verbose_name': 'Клієнтський контракт (Київ), звіт по авто по ТО за період',
                'verbose_name_plural': 'Клієнтські контракти (Київ), звіт по авто по ТО за період',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cars_rental.clientcontractkyiv',),
        ),
    ]
