# Generated by Django 3.0.3 on 2020-10-13 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0127_clientcontractfullcarreportkyiv'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcontracttimetablekyiv',
            options={'verbose_name': 'Клієнтський контракт (Київ), графік погашення', 'verbose_name_plural': 'Клієнтський контракт (Київ), графік погашення'},
        ),
    ]
