# Generated by Django 3.0.3 on 2020-10-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0128_auto_20201013_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcontracttimetablelviv',
            options={'verbose_name': 'Клієнтський контракт (Львів), графік погашення', 'verbose_name_plural': 'Клієнтський контракт (Львів), графік погашення'},
        ),
    ]
