# Generated by Django 3.0.3 on 2020-10-15 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0129_auto_20201013_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcontracttokyiv',
            options={'verbose_name': 'Клієнтський контракт, ТО (Київ)', 'verbose_name_plural': 'Клієнтський контракт, ТО (Київ)'},
        ),
        migrations.AlterModelOptions(
            name='clientcontracttolviv',
            options={'verbose_name': 'Клієнтський контракт, ТО (Львів)', 'verbose_name_plural': 'Клієнтський контракт, ТО (Львів)'},
        ),
        migrations.AlterModelOptions(
            name='clientcontracttotodaykyiv',
            options={'verbose_name': 'Клієнтський контракт, ТО (Київ); введення даних', 'verbose_name_plural': 'Клієнтський контракт, ТО (Київ); введення даних'},
        ),
        migrations.AlterModelOptions(
            name='clientcontracttotodaylviv',
            options={'verbose_name': 'Клієнтський контракт, ТО (Львів); введення даних', 'verbose_name_plural': 'Клієнтський контракт, ТО (Львів); введення даних'},
        ),
    ]
