# Generated by Django 3.0.3 on 2020-10-19 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0130_auto_20201015_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontractkyiv',
            name='investor_full_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.InvestorKyiv'),
        ),
        migrations.AlterField(
            model_name='clientcontractlviv',
            name='investor_full_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.InvestorKyiv'),
        ),
    ]
