# Generated by Django 3.0.3 on 2020-10-19 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0131_auto_20201019_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontractkyiv',
            name='car',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.CarKyiv', verbose_name='Авто'),
        ),
        migrations.AlterField(
            model_name='clientcontractkyiv',
            name='city',
            field=models.CharField(default='Київ', max_length=10, verbose_name='Місто, де заключений контракт'),
        ),
        migrations.AlterField(
            model_name='clientcontractkyiv',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.ClientKyiv', verbose_name='ПІБ клієнта'),
        ),
        migrations.AlterField(
            model_name='clientcontractkyiv',
            name='investor_full_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.InvestorKyiv', verbose_name='ПІБ інвестора'),
        ),
        migrations.AlterField(
            model_name='clientcontractlviv',
            name='city',
            field=models.CharField(default='Київ', max_length=10, verbose_name='Місто, де заключений контракт'),
        ),
        migrations.AlterField(
            model_name='clientcontractlviv',
            name='investor_full_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.InvestorKyiv', verbose_name='ПІБ інвестора'),
        ),
    ]
