# Generated by Django 3.0.3 on 2020-10-19 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0132_auto_20201019_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontractlviv',
            name='car',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.CarLviv', verbose_name='Авто'),
        ),
        migrations.AlterField(
            model_name='clientcontractlviv',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.ClientLviv', verbose_name='ПІБ клієнта'),
        ),
        migrations.AlterField(
            model_name='clientcontractlviv',
            name='investor_full_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.InvestorLviv', verbose_name='ПІБ інвестора'),
        ),
    ]
