# Generated by Django 3.0.3 on 2020-11-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0133_auto_20201019_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontractlviv',
            name='city',
            field=models.CharField(default='Львів', max_length=10, verbose_name='Місто, де заключений контракт'),
        ),
    ]
