# Generated by Django 3.0.3 on 2020-11-05 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0134_auto_20201105_1117'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Branch',
            new_name='BranchHead',
        ),
    ]
