# Generated by Django 3.0.3 on 2020-11-05 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0137_auto_20201105_1138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branchhead',
            options={'verbose_name': 'Керівники відділень', 'verbose_name_plural': 'Керівники відділень'},
        ),
    ]
