# Generated by Django 3.0.3 on 2020-11-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0138_auto_20201105_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Номер відділення')),
                ('city', models.CharField(max_length=25, verbose_name='Місто')),
                ('full_name', models.CharField(max_length=50, null=True, verbose_name='ПІБ директора фірми/філіалу фірми:')),
            ],
            options={
                'verbose_name': 'Відділення',
                'verbose_name_plural': 'Відділення',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='BranchHead',
        ),
    ]
