# Generated by Django 3.0.3 on 2020-11-05 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0139_auto_20201105_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_field', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.Branch')),
            ],
        ),
    ]
