# Generated by Django 3.0.3 on 2020-11-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0141_auto_20201105_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontractkyiv',
            name='director_full_name',
            field=models.CharField(default='Шевченко Юрій', max_length=50, verbose_name='ПІБ директора фірми/філіалу фірми'),
        ),
        migrations.AlterField(
            model_name='clientcontractlviv',
            name='director_full_name',
            field=models.CharField(default='Директор львівського відділення', max_length=50, verbose_name='ПІБ директора фірми/філіалу фірми'),
        ),
    ]
