# Generated by Django 3.0.3 on 2020-06-03 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0058_auto_20200603_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientcontract',
            name='commercial_course_usd_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.ExchangeRateKyiv'),
        ),
    ]
