# Generated by Django 3.0.3 on 2020-06-03 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_rental', '0060_remove_clientcontract_commercial_course_usd_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcontract',
            name='commercial_course_usd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars_rental.ExchangeRateKyiv'),
        ),
    ]
